'''
Even Fibonacci numbers
https://www.projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


import time
TEST_CYCLES = 10
'''
1st approach:
- Use 2 value to store the most 2 recent fibo number, use those to generate the next number. Swap the new number with smaller value. 
- If new number is even, add it to sum
Space complexity: 0(1)
'''

def sum_fibo(limit):
  prev_val, curr_val = 1, 2
  res = 2
  while curr_val <= limit:
    curr_val = prev_val + curr_val
    prev_val = curr_val - prev_val
    if curr_val % 2 == 0:
      res += curr_val
  
  return res

'''
2nd approach:
Only third fibo number are even, so we only add those.
Space complexity: 0(1)
'''
def sum_fibo_even(limit):
  a, b, c  = 1, 1, 2
  res = 0
  while c < limit:
    res += c
    a = b + c
    b = c + a
    c = a + b
  return res

'''
3r approach:
Use the math relationship between even Fibonaci number
E(n) = 4*E(n-1) + E(n-2)
Space complexity: 0(1)
'''
def sum_fibo_math(limit):
  prev_val, curr_val = 2, 8  
  res = 10
  while curr_val < limit:
    #print(curr_val)
    curr_val = prev_val + 4 * curr_val
    prev_val = (curr_val - prev_val)/4
    res += curr_val
  res -= curr_val
  return res

def averageTimeTaken(method, target):
  sumTimeTaken = 0
  for _ in range(TEST_CYCLES):
    start = time.process_time()
    method(target)
    sumTimeTaken += time.process_time() - start
  return sumTimeTaken / float(TEST_CYCLES)

def overalTest(target):

  print("Testing with target = ", target)
  print("First approach")
  print("Value: ", sum_fibo(target))
  print("Average time Taken: ", averageTimeTaken(sum_fibo,target))

  print("Second approach")
  print("Value: ", sum_fibo_even(target))
  print("Average time Taken: ", averageTimeTaken(sum_fibo_even,target))

  print("Third approach")
  print("Value: ", sum_fibo_math(target))
  print("Average time Taken: ", averageTimeTaken(sum_fibo_math,target))
  print("\n")


overalTest(4000000)
overalTest(400000000)
overalTest(400000000000)

# Testing with target =  4000000
# First approach
# Value:  4613732
# Average time Taken:  0.0
# Second approach
# Value:  4613732
# Average time Taken:  0.0
# Third approach
# Value:  4613732
# Average time Taken:  0.0


# Testing with target =  400000000   
# First approach
# Value:  350704366
# Average time Taken:  0.0
# Second approach
# Value:  350704366
# Average time Taken:  0.0
# Third approach
# Value:  350704366
# Average time Taken:  0.0


# Testing with target =  400000000000
# First approach
# Value:  478361013020
# Average time Taken:  0.0
# Second approach
# Value:  478361013020
# Average time Taken:  0.0
# Third approach
# Value:  478361013020
# Average time Taken:  0.0